### ISSUE TITLE
Unable to render a react-side-bar

### ISSUE THREAD

**Issue by hlindley-ccssi** [mschez/react-side-bar#3]
I can't seem to render the component using the simplest implementation.  I keep getting the error: 

Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `NewestNav`

import React from 'react';
import ReactDOM from 'react-dom';

import SideBar from 'react-side-bar';

const NewestNav = React.createClass({

  render() {
    return (
      <SideBar
    bar={(<div>Amazing Sidebar</div>)}
    size={300} />
    );
  },
});

module.exports = NewestNav;

**Comment by mschez** [comment]
Hi, yes, sorry for this issue. It is a bug introduced in last version. I am trying solve it. If you want to test the component, you can pin version 0.3.2 in your `package.json`.
Thank you for your support.

**Comment by hlindley-ccssi** [comment]
Thanks, but i tried all versions going back to 0.2.2 and i still have the same issue.

**Comment by mschez** [comment]
Yes, you are right. I had an error in the way which the module are exported. Sorry for this. It was fixed in v0.3.5, try execute `npm install` and tell me the result please.
Thank you for your support.

**Comment by hlindley-ccssi** [comment]
Thanks!  The basic implementation that I describe above is still not rendering (no errors), but the kitchen sink example works.

**Comment by mschez** [comment]
Ok, the code you wrote in your first comment is your implementation? Looks a incomplete implementation, can you edit and format code please?
